### ISSUE TITLE
Finish off library page

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#104]
# Overview

The first version of the library page is handled in #69. Here all minor outstanding issues. Partially blocked requiring an additional information.

# Tasks

- [ ] Searching by topic hides all facets on the left (expected?)
- [ ] Give feedback href
- [ ] Design for blog posts?
- [ ] Share functionality (probably needs a dropdown)
- [ ] JS to populate topic description box on large screens (as mentioned [here](https://github.com/okfn/ckanext-lacounts/compare/library#diff-fa9acadc11a10d2f0ab1df8c7cc6194dR65))

**Comment by amercader** [comment]
Main pending thing here is what to do with the topics images, remove or just keep the names? Clarify with the client

**Comment by roll** [comment]
@smth 
So regarding stories creation.

This page is not exposed anywhere - http://ckan-dev:5000/story/new

So we probably need to add another way to create stories UI-wise (on the library page?).

**Comment by amercader** [comment]
@smth also please questions for you:

* Can the story image size in the search results be further reduced?
* Can the smaller scale images go under the yellow title line?

**Comment by amercader** [comment]
Pending tasks:

@roll:

- [ ] Display label for story type instead of "Story" in stories results

@smth 

- [ ] Add a helper button like the one on the featured viz on the home page (question mark) that opens a popup with a helper text. It should behave in the same way as the home page one (opened the first time, close on next visits). Wherever you think it makes sense.
- [ ] Concern about how to start new searches once you've scrolled down:
  * Proposed solution was to add a "Jump to the top" button
  * Alternative is to have a small search box on the sticky header but that has an impact on the overall design

**Comment by smth** [comment]
What is the thing(s) that people need help with (that lead to the suggestion of the helper button)?

**Comment by amercader** [comment]
@roll 

- [  ] Topics pills not appearing when filtering by topic
- [ ] Show X results text moves to the left when selecting a filter

@smth 

- [ ] Clear all button/link when selecting a filter

Pending from the client:

* Helper text

**Comment by smth** [comment]
https://github.com/okfn/ckanext-lacounts/compare/finalize-library-page

("Remove all" currently doesn't do anything)

**Comment by roll** [comment]
@roll 
- [ ] make "Remove all" do something
