### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#105]
# Overview

This is a following of #63 and previous to #91 

# Tasks

- [x] connect recent stories
- [x] connect community topics
- [x] fix all small things from #91 that possible now
