### ISSUE TITLE
OpenLayers (wms/wfs/etc) map view doesn't work properly

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#11]
# Overview

We use a fork with bootstrap2 bundled - https://github.com/roll/ckanext-geoview. 

The GeoJSON view works but OpenLayers (wms, wfs formats) still doesn't with no errors:

![ol](https://user-images.githubusercontent.com/557395/43629110-fafeff30-9704-11e8-8de1-560a72928833.png)

# Tasks

- [ ] fix OpenLayers issue
- [ ] PR the main repo
- [ ] Rebase on the main repo in `Dockerfile.dev`

**Comment by amercader** [comment]
We can park this for now unless we actually need to preview WMS services
