### ISSUE TITLE
Finalize dataset page

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#111]
# Overview

To log all outstanding issue after #71 

# Tasks

- [ ] add a link for completion rate documentation (click on the circle to see the empty link)

**Comment by roll** [comment]
Resource error:
```
File '/srv/app/src/ckan/ckan/controllers/package.py', line 1142 in resource_read
  return render(template, extra_vars=vars)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src/ckanext-scheming/ckanext/scheming/templates/scheming/package/resource_read.html', line 9 in top-level template code
  {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 3 in top-level template code
  {% set res = c.resource %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/package/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-hierarchy/ckanext/hierarchy/templates/package/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/package/base.html', line 3 in top-level template code
  {% set pkg = c.pkg_dict or pkg_dict %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/page.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/srv/app/src_extensions/ckanext-geoview/ckanext/geoview/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-googleanalytics/ckanext/googleanalytics/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src_extensions/ckanext-harvest/ckanext/harvest/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/base.html', line 101 in top-level template code
  {%- block page %}{% endblock -%}
File '/srv/app/src/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 22 in block "content"
  {% block main_content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 53 in block "main_content"
  {% block pre_primary %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 22 in block "pre_primary"
  {% block resource %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 24 in block "resource"
  {% block resource_inner %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 92 in block "resource_inner"
  {% block data_preview %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 93 in block "data_preview"
  {% block resource_view %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 106 in block "resource_view"
  {% block resource_view_content %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 116 in block "resource_view_content"
  {% snippet 'package/snippets/resource_view.html',
File '/srv/app/src/ckan/ckan/lib/jinja_extensions.py', line 268 in _call
  return base.render_snippet(args[0], **kwargs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 84 in render_snippet
  output = render(template_name, extra_vars=kw)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src_extensions/ckanext-pdfview/ckanext/pdfview/theme/templates/package/snippets/resource_view.html', line 3 in top-level template code
  {% block resource_view %}
File '/srv/app/src_extensions/ckanext-pdfview/ckanext/pdfview/theme/templates/package/snippets/resource_view.html', line 24 in block "resource_view"
  {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
File '/srv/app/src/ckan/ckan/lib/jinja_extensions.py', line 268 in _call
  return base.render_snippet(args[0], **kwargs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 84 in render_snippet
  output = render(template_name, extra_vars=kw)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src/ckan/ckan/templates/package/snippets/resource_view_filters.html', line 5 in top-level template code
  data-module-fields="{{ h.dump_json(h.resource_view_get_fields(resource)) }}"
File '/srv/app/src/ckan/ckan/lib/helpers.py', line 2286 in resource_view_get_fields
  result = logic.get_action('datastore_search')({}, data)
File '/srv/app/src/ckan/ckan/logic/__init__.py', line 384 in get_action
  raise KeyError("Action '%s' not found" % action)
KeyError: "Action 'datastore_search' not found"
```

**Comment by roll** [comment]
Resource error:
```
File '/srv/app/src/ckan/ckan/controllers/package.py', line 1142 in resource_read
  return render(template, extra_vars=vars)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src/ckanext-scheming/ckanext/scheming/templates/scheming/package/resource_read.html', line 9 in top-level template code
  {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 3 in top-level template code
  {% set res = c.resource %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/package/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-hierarchy/ckanext/hierarchy/templates/package/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/package/base.html', line 3 in top-level template code
  {% set pkg = c.pkg_dict or pkg_dict %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/page.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/srv/app/src_extensions/ckanext-geoview/ckanext/geoview/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-googleanalytics/ckanext/googleanalytics/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src_extensions/ckanext-lacounts/ckanext/lacounts/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src_extensions/ckanext-harvest/ckanext/harvest/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/base.html', line 101 in top-level template code
  {%- block page %}{% endblock -%}
File '/srv/app/src/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 22 in block "content"
  {% block main_content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 53 in block "main_content"
  {% block pre_primary %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 22 in block "pre_primary"
  {% block resource %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 24 in block "resource"
  {% block resource_inner %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 92 in block "resource_inner"
  {% block data_preview %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 93 in block "data_preview"
  {% block resource_view %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 106 in block "resource_view"
  {% block resource_view_content %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 116 in block "resource_view_content"
  {% snippet 'package/snippets/resource_view.html',
File '/srv/app/src/ckan/ckan/lib/jinja_extensions.py', line 268 in _call
  return base.render_snippet(args[0], **kwargs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 84 in render_snippet
  output = render(template_name, extra_vars=kw)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src_extensions/ckanext-pdfview/ckanext/pdfview/theme/templates/package/snippets/resource_view.html', line 3 in top-level template code
  {% block resource_view %}
File '/srv/app/src_extensions/ckanext-pdfview/ckanext/pdfview/theme/templates/package/snippets/resource_view.html', line 24 in block "resource_view"
  {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
File '/srv/app/src/ckan/ckan/lib/jinja_extensions.py', line 268 in _call
  return base.render_snippet(args[0], **kwargs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 84 in render_snippet
  output = render(template_name, extra_vars=kw)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src/ckan/ckan/templates/package/snippets/resource_view_filters.html', line 5 in top-level template code
  data-module-fields="{{ h.dump_json(h.resource_view_get_fields(resource)) }}"
File '/srv/app/src/ckan/ckan/lib/helpers.py', line 2286 in resource_view_get_fields
  result = logic.get_action('datastore_search')({}, data)
File '/srv/app/src/ckan/ckan/logic/__init__.py', line 384 in get_action
  raise KeyError("Action '%s' not found" % action)
KeyError: "Action 'datastore_search' not found"
```

**Comment by smth** [comment]
Tags background colour is due to the `well` class sneaking back in. That should be removed from `tag-list`.

**Comment by roll** [comment]
@smth 
@amercader
I fixed/deployed tags and moved the resource issue (if it's not related to the dataset work) - https://github.com/okfn/ckanext-lacounts/issues/113

**Comment by amercader** [comment]
Main issue, pending feedback comments is the styling of the resource listings

**Comment by amercader** [comment]
List of new tasks:

@roll 

- [ ] Search on the dataset page does not work
- [ ] Please always display “find related datasets” in the left sidebar. Noticed this section disappears if there are no related datasets. We’ll work to find an alternative link, in situations when datasets may not be assigned a site-specific topic
- [ ] Display “stories that reference this data” section in L sidebar. If there aren't any add the “suggest a data story” link when no stories refer to the specific dataset
- [ ]  Remove Publisher’s tags (the grey tags above the Metadata section) from public view. While we want to utilize publisher tags to inform our own tagging, we don’t want to display them to users


@smth 

- [ ] Description should be limited to a handful of lines on page load (number of lines up for discussion), with a “more” type of link that expands it. A long description right now will push the rest of the page content too far down. (AM: I believe we've done this in the past)
-[ ] Spacing between Description and “Data and Resources” could be increased, seems cramped as-is… but open for discussion!

- [ ] mobile: The layout probably should be reworked. The Title and Description do not display at the top of the view. (See images on comments doc for this and the next issues)
- [ ] mobile:The Metadata completion rate text is not vertically aligned with the bar (as it is on the desktop view)
- [ ] mobile:The dataset resource page’s layout might need reworking

**Comment by smth** [comment]
First four of my items are in https://github.com/okfn/ckanext-lacounts/pull/129. Will do the last one separately as that's a new page, which hasn't been started yet.

**Comment by amercader** [comment]
New tasks:

@roll 

- [ ] Order resources in resource listing by what’s directly downloadable. I guess we can use a helper function just before calling the resouce listing snippet.
- [ ] Resource page: rename “From the dataset abstract” to “From the dataset description”
- [ ] Resource page: Change “resources” header (left-hand column)  to read “other formats”

@smth 

- [ ] Placeholder for Treding (fire) icon
- [ ] Reduce format icons
- [ ] Show title in whole round buttons (not just image)
- [ ] The icons for GeoJSON and KML formats are not shown correctly ([example](http://localhost:5000/dataset/very-high-fire-hazard-severity-zones)). The sprite for these comes from [ckanext-geoview](https://github.com/ckan/ckanext-geoview/blob/master/ckanext/geoview/public/img/gis-resources-sprite-icons.png) ([css](https://github.com/ckan/ckanext-geoview/blob/master/ckanext/geoview/public/css/geo-resource-styles.css)). I guess we can override the css from the lacounts.extensions
![screenshot_2018-10-29 very high fire hazard severity zones - ckan](https://user-images.githubusercontent.com/200230/47653985-2b1b9d80-db8a-11e8-968e-814108568863.png)

**Comment by roll** [comment]
csv resources on staging:

![csv](https://user-images.githubusercontent.com/557395/47775529-f9791280-dd00-11e8-8483-9f6af01ec937.png)

**Comment by roll** [comment]
Resources meta:

![meta](https://user-images.githubusercontent.com/557395/47776220-f3843100-dd02-11e8-8321-b6a32c15adc6.png)

**Comment by roll** [comment]
@smth 
Could you please take a look at this one (dataset/library page) - https://lacounts-staging.l3.ckan.io/dataset/mental-health-centers

![tracking](https://user-images.githubusercontent.com/557395/47851920-243f9580-ddeb-11e8-9f62-b456bd6a6531.png)

It's defined at `snippets/popular.html` and styled at `css/icons`. It's a mystery for me that it's underlined...

**Comment by smth** [comment]
@roll looks like that's just the design of the icon https://fontawesome.com/v4.7.0/icon/fire

It's not the icon we are going to use, but you can use it for now, and I'll replace it.

**Comment by roll** [comment]
@smth 
Hah funny that's it) Yea please replace it. I tried to use the default ckan icon but I wasn't able to make it bigger.

**Comment by smth** [comment]
Stuff from checklist is in https://github.com/okfn/ckanext-lacounts/pull/140

**Comment by roll** [comment]
@amercader 
We still have a few problems here - https://lacounts-staging.l3.ckan.io/dataset/enterprise-systems-catalog/resource/95d6000b-f329-48f4-b6b2-16fd72a23281

**Comment by roll** [comment]
@roll 
- [ ] remove 'field-value' from dataset's metadata
- [ ] remove `field-value' from resource's metadata
