### ISSUE TITLE
Improve metadata schema and form

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#14]
# Overview

In #12 we have created the initial metadata schema (#6). Next, we need to polish it using the feedback from LA Counts.

# Resources

see the Google Doc

# Tasks

- [ ] clarify some fields
- [ ] figure out which fields required
- [ ] clarify resource schema
- [ ] TBD
