### ISSUE TITLE
Finalize topics page

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#150]
# Overview

For now, https://lacounts-staging.l3.ckan.io/topic

# Tasks

@roll 
  - [x] replace placeholder - stories count for a topic
  - [x] sync `topic.featured` behaviour for `homepage/topics` (check for yes/no)
  - [x] on the `topic` page `datasets` -> `datasets and stories`

@smth 
  - [x] implement proper `topic` page design

**Comment by smth** [comment]
Topic page is in https://github.com/okfn/ckanext-lacounts/pull/152.

**Comment by roll** [comment]
DONE
