### ISSUE TITLE
Rich-text editor, datasets embedding and rendering for stories

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#16]
#  Overview

By default, the `ckanext-showcase` plugin only supports plain textarea descriptions written in text/markdown. In this issue, we have to extend the current functionality by a rich-text editor and with an ability to embed existent dataset resources as a part of text/markdown content like:

``` 
This is my story with embedded dataset:
[dataset/id/view]
```

Also for now, `ckanext-showcase` allow to link datasets but only on the update stage. But internally it supports linking. The idea is to use one of JavaScript client-side text/markdown editor extending it to support embedded datasets. At the same time, we need to add embedded datasets as linked datasets.

I think we better use rich **markdown** editor instead of **html** editor:
- for the users, UI is very close
- markdown is native for ckan (rendering/security etc)
- it will simplify the embedding feature (cleaner workflow)

# Tasks

- [x] fork `ckanext-showcase` plugin and change its database
- [x] fix bootstrap problems with ckan2.8
- [x] select JavaScript library to use as an editor:
    - https://simplemde.com/
    - http://ui.toast.com/tui-editor/
    - https://benweet.github.io/stackedit.js/
    - etc
- [x] replace textarea used for story description by the editor
- [x] on save add every embedded dataset as linked dataset if it's easy to implement
- [x] on read render `showcase.description` with a markdown renderer 
- [x] show it instead of default showcase's description
- [x] render and incorporate into the article embedded datasets (with iframes?)
- [x] clean the code up 
- [x] merge into `okfn/cknext-showcase/stories`
