### ISSUE TITLE
Ability to enable/disable comments per story

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#18]
# Overview

> https://github.com/ckan/ckanext-disqus

We use the `ckanext-disquss` plugin. It allow to enable comments for arbitrary page adding `{{h.disqus_comments()}}` to a template. Introducing enable/disable commenting flag we can show/hide the Disqus widget per story.

# Tasks

- [x] add comments to the read story view
- [ ] add `showcase.is_comments_enabled` field
- [ ] use this field to show/hide comments per story
