### ISSUE TITLE
Finalize rich-text editor for stories

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#21]
# Overview

For now, we use SimpleMDE editor for rich-text editing experience. It's a great editor but there are a few concerns:
- despite having more than 5000 stars, the main repo currently doesn't have a maintainer
- business rules could require more complex WYSIWYG behavior that Markdown can provide

# Tasks

- [ ] formulate exact text editing/presentation requirements (like we need a button to create `<span class="">..</span>` and etc)
- [ ] reconsider a library to use (trying to minimize the customization work needed to meet the requiremetns). Links to demos:
  - MarkDown
    - SimpleMDE - https://simplemde.com/ (current)
    - TUIEditor - http://ui.toast.com/tui-editor/
    - StackEdit - https://benweet.github.io/stackedit.js/
    - etc
  - HTML
    - Quill - https://quilljs.com/playground/
    - MediumEditor - https://yabwe.github.io/medium-editor/
    - Pell - https://jaredreich.com/pell
    - Trix - https://trix-editor.org/
    - SummerNote - https://summernote.org/
    - etc
  - MarkDow + HTML
    - Pen - https://sofish.github.io/pen/
    - etc
- [ ] add needed customizations

# Notes

We use `iframe` for datasets/external embedding. The editor should allow using it.

**Comment by roll** [comment]
@amercader 
@smth 
I've updated this issue to focus on text editing/presentation.
