### ISSUE TITLE
Rebase on official ckan extensions when possible

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#46]
# Overview

For now, we use several okfn forks:
- https://github.com/okfn/ckanext-hierarchy
- https://github.com/okfn/ckanext-showcase
- https://github.com/okfn/ckanext-geoview
- https://github.com/okfn/ckanext-pdfview

# Tasks
- [ ] propose fixes to `ckanext-geoview` and rebase on the official repo
- [ ] propose fixes to `ckanext-pdfview` and rebase on the official repo
- [ ] propose fixes to `ckanext-hierarchy` and rebase on the official repo (?)
- [ ] establish as an independent plugin `okfn/ckanext-story` without merging to upstream (?):
  - [ ] https://github.com/okfn/ckanext-showcase/issues/10
  - [ ] https://github.com/okfn/ckanext-showcase/issues/11
- [ ] ensure that we usse only tagged sources for Dockerfiles in staging/production
