### ISSUE TITLE
Normalize socrata harvested datasets

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#52]
# Overview

Harvested metadata will obviously have a different schema than the LA Counts site one. We need a way to match fields in the remote metadata to the ones expected in our site.

Or in this [Socrata dataset](http://api.us.socrata.com/api/catalog/v1?ids=r8vi-rxcc) from this [site](https://data.smgov.net), the value for `response['results']['classification']['domain_metadata']['key'] == 'Data-Freshness_Time-Period'` might be our `temporal_extent_start` / `temporal_extent_end` fields (need to check this).

Mapping cheat sheet - https://github.com/okfn/ckanext-lacounts/issues/51#issuecomment-418265966

# Tasks 

- [x] https://controllerdata.lacity.org
- [x] https://data.smgov.net
- [ ] more TBD (?) @amercader

**Comment by brew** [comment]
Added the two Socrata sources named above. I've added publishers but they may not be exactly the ones wanted for production.

**Comment by brew** [comment]
Similarly, the `license` property is available under the `metadata` key for Socrata datasets. It's not clear if the provided values are part of a controlled vocabulary. By default in CKAN, license options for a dataset are provided by entries to the [Open Licenses Service](https://licenses.opendefinition.org/) for a controlled CKAN licenses group (https://licenses.opendefinition.org/licenses/groups/ckan.json). If Socrata `metadata.license` is free text it maybe difficult to map between these two properties.

**Comment by amercader** [comment]
Some queries

* [Frequency 1](https://lacounts-staging.l3.ckan.io/api/action/package_search?q=Update-Information_Refresh-Rate:[* TO *]&facet=true&facet.field=["Update-Information_Refresh-Rate"]&rows=0) (Controller)

* [Frequency 2](https://lacounts-staging.l3.ckan.io/api/action/package_search?q=Data-Freshness_Update-Frequency:[*%20TO%20*]&facet=true&facet.field=[%22Data-Freshness_Update-Frequency%22&rows=0) (Santa Monica)

* [Time period](https://lacounts-staging.l3.ckan.io/api/action/package_search?q=Data-Freshness_Time-Period:[*%20TO%20*]&facet=true&facet.field=[%22Data-Freshness_Time-Period%22]&rows=0) (Santa Monica)

**Comment by amercader** [comment]
Some fixes / tweaks on our side:

* `harvest_dataset_url` extra should contain the link to the specific dataset page in the source catalog
* Use the `["resource"]["owner"]["display_name"]` value as our `contact_name` field

**Comment by roll** [comment]
@amercader 
Are we good enough with this issue:
https://lacounts-staging.l3.ckan.io/dataset/calendar-events
