### ISSUE TITLE
Normalize esri harvested datasets

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#53]
# Overview

Harvested metadata will obviously have a different schema than the LA Counts site one. We need a way to match fields in the remote metadata to the ones expected in our site.

# Tasks

- [ ] http://geohub.lacity.org
- [ ] http://gisdata-scag.opendata.arcgis.com/
- [ ] https://services5.arcgis.com/YzWImMY4GtDcMxOx/ArcGIS/rest/services
- [ ] more/less TBD (?) @amercader

**Comment by amercader** [comment]
Some fixes on our side for the Geoportal harvester:

* The contact email is not getting imported. This is an issue at the ckanext-dcat level but we might just fix it in our own profile for now
* The coordinates in the Spatial coverage (Text) field need to be converted to a a GeoJSON object and stored in the `spatial` field instead (eg `{ "type": "Polygon", "coordinates": [ [ [minx, miny],[minx, maxy], [maxx, maxy], [maxx, miny], [minx, miny] ] ] }`)
* The  `harvest_*` fields need to be filled

**Comment by roll** [comment]
@amercader 
Please check if we're good now to close this issue:
https://lacounts-staging.l3.ckan.io/dataset/elections1

Also, the PR to review for it: https://github.com/okfn/ckanext-lacounts/pull/79
