### ISSUE TITLE
Blog feature

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#55]
The blog will show stories relating to LA Counts itself. The underlying stories will be exactly the same as the other ones, but they will have a flag that marks them as blog posts.

Blog posts will be shown on a dedicated page (`/blog`), ordered by most recent on top

### Tasks

- [x] @roll
  - [x] Add a new routes (`/blog` and `/blog/{name}`) using `IRoutes`
  - [x] Add a new type to the stories type field (Blog post) - `showcase.story_type`
  - [x] View function that queries all stories of type `blog_post` (or 5 / 10 first) and renders the blog template
- [x] @smth 
  - [x] Design blog pages (@smth) This should be a really simple list/grid of posts. If possible, the actual post page should be the same as normal story one.
  - [x] Build blog template(s)
- [x] decide/update on showing blog posts at http://ckan-dev:5000/dataset

**Comment by smth** [comment]
The original design for the blog index was as described above. Two notable pieces of feedback:

- A desire for continuous scroll
- A desire for blog only search (I think this might confuse things)

**Comment by smth** [comment]
Index layout in https://github.com/okfn/ckanext-lacounts/pull/153.

**Comment by roll** [comment]
@roll 
  - [ ] update breadcrumbs for blog posts (now it uses `stories`)

**Comment by roll** [comment]
DONE
