### ISSUE TITLE
Implement Dataset page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#71]
# Overview

Based on the design in Figma (shown at the bottom as of 20180920, it can be bound to change):

Things to note:

* Don't implement the ratings widget yet, but keep it mind as it might come back in the future.
* The metadata section should only contain the actual metadata fields. Things like related stories and datasets have their own section in the left bar, and the harvesting stuff should be displayed separately. 
* We are waiting on confirmation about which fields are used to calculate the Metadata Completion index.

# Tasks

- [x] Add Disqus
- [x] Manage button for sysadmins?
- [x] Replace hardcoded content in publisher box
- [x] Replace hardcoded completion rate
- [x] Replace hardcoded tags
- [x] Replace hardcoded topics
- [x] Replace hardcoded metadata
- [ ] Replace hardcoded related stories

---

![dataset - desktop](https://user-images.githubusercontent.com/200230/45816821-13284280-bcdd-11e8-9669-30c10e5aba98.png)

**Comment by roll** [comment]
As discussed with Sam - I'm ready to start working on internal implementation bits after I have finished #69

**Comment by smth** [comment]
Layout worked added here https://github.com/okfn/ckanext-lacounts/tree/dataset

TO DO:

- [ ] Replace hardcoded content in publisher box
- [ ] Replace hardcoded related stories
- [ ] Replace hardcoded tags
- [ ] Replace hardcoded metadata
- [ ] Replace hardcoded figures in completion rate chart dropdown
- [ ] Add Disqus
