### ISSUE TITLE
Implement Story page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#73]
# Overview

Based on the design in Figma (shown at the bottom as of 20180920, it can be bound to change):

Things to note:

* ~~Is the image shown at the beginning of the context (parking meter) required? ie is it expected to always be there? Also it is the same that will be used as featured image when displaying a story listing?~~ Done
* Pull quotes: implementation for this needs to be clarified. It can be done in a separate issue.
 
# Tasks

- [x] connect about the author
- [x] skip methodology
- [x] connect datasets in story
- [x] remove topics
- [ ] ---
- [x] connect title/author
- [x] connect tags
- [ ] connect lead
- [ ] connect description
- [ ] connect featured image
- [ ] ---
- [x] connect related stories

---

![story - desktop](https://user-images.githubusercontent.com/200230/45817557-6c917100-bcdf-11e8-9e74-d007c0014064.png)
