### ISSUE TITLE
Finalize home page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#91]
# Overview

We have to finish the homepage.

# Tasks

- [ ] Featured visualization
    - [x] Featured visualization title is hardly visible (because of the text color)
    - [ ] Featured visualization link doesn't work
    - [x] Make the Featured visualization header more prominent
- [x] What's happening
    - [x] Join mailing list link doesn't work
    - [x] Source code link doesn't work
    - [x] Folow us on twitter link doesn't work
- [x] Community topics
    - [x] Fix topic links (they should use `?groups=education`, not `?topic=xx`)
- [x] Recent data stories
    - [x] View all stories link doesn't work
    - [x] Show actual stories in Recent Data Stories (requires #89)
- [x] Community
    - [x] Suggest a story link doesn't work
    - [x] Suggest a dataset link doesn't work
- [x] Footer
    - [x] FAQs link doesn't work 
    - [x] Terms of services link doesn't work 
    - [x] Privacy policy link doesn't work 
    - [x] Contact us / feedback link doesn't work 
    - [x] Resources link doesn't work 
    - [x] Github icon link doesn't work 
- [x] Visual design 
    - [x] Links like featured visualization/view all stories have a weird hovered look (an icon)
    - [x] Topic and stories pictures are not clickable

@roll @smth Please add anything that I've missed

**Comment by roll** [comment]
OK. We've done everything except for the things requiring additional information (like links etc)

**Comment by smth** [comment]
Above done in https://github.com/okfn/ckanext-lacounts/pull/130

**Comment by roll** [comment]
@roll
- [ ] About should be underlined when selected
- [ ] Switch publishers/topics in the header
