### ISSUE TITLE
Implement Publishers page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#93]
# Overview
@roll Perhaps you can do the bulk of the work on this one, including (see tasks). 
And then @smth can just do the final design touches.

# Tasks

- [x] add title and main paragraph about publishers
- [x] move the `add publisher` button to the right (see library)
- [ ] display publisher names in column, expanding children publishers
- [ ] filter by name on the left
- [x] filter by type on the left

---

![publishers - desktop](https://user-images.githubusercontent.com/200230/46610214-62a6a500-cb0a-11e8-8a8d-0e83d23b233d.png)
(Design on Figma as of 20181008)
